<#
tools/verify.ps1 - the single local entry point for every judgement criterion.

Why this exists
---------------
The spec used to describe the local criteria in prose ("the local three certificates") without ever naming
them: which ones, how many, which command - all of it left to the reader's memory. A gate list that lives in
memory is the very disease this process treats. This script names the criteria, runs ALL of them, and prints
one summary (CONTRIBUTING.md section 6.1).

Criteria
--------
  1. build       {{BUILD_GATE_CMD}}      (the stack's own bar for "green": for a stack that expresses
                                          "zero warnings" as an error, this command IS that bar)
  2. test        {{TEST_CMD}}
  3. governance  tools/governance-check.ps1 -Range <range> -Branch <branch> -Strict all
  4. metrics     tools/metrics.ps1 -Check
  5. kanban      tools/build-kanban.ps1 (artifact) then tools/kanban-check.ps1 (gate)
  6. smoke       {{SMOKE_CMD}}           (the I1 trunk-runnable invariant: build -> start -> one real request)

UNGUARDED is not a pass
-----------------------
A criterion prints UNGUARDED - not PASS, not FAIL - in two cases:
  * the command renders as the angle-bracketed hint '<...>' because the stack ships no command for it
    ({{SMOKE_CMD}} for a stack with no smoke command, {{BUILD_GATE_CMD}} for -Stack generic);
  * the carrier script is absent (a repo that deleted tools/kanban*.ps1 on purpose).
CONTRIBUTING.md section 8.1: a constraint that cannot be written down must be declared SOFT or UNGUARDED -
never faked with a command that trivially passes. That is why this script never runs a placeholder command:
an empty pass is worse than an honest gap, because it stops the human check that would have caught it.

Why NOT fail-fast: fixing one red and then re-running the whole set is what makes people stop running the
whole set. One run must show every red at once.

Writes: nothing tracked (tools/kanban.html is regenerated by build-kanban.ps1 and kept out of the repo).

Usage
-----
  powershell -ExecutionPolicy Bypass -File tools/verify.ps1
  powershell -ExecutionPolicy Bypass -File tools/verify.ps1 -Fast        # docs + board only
  powershell -ExecutionPolicy Bypass -File tools/verify.ps1 -Range "origin/develop...HEAD" -Branch "P2-2-local-gate"

Exit codes: 0 all criteria passed / 1 at least one FAILED / 2 cannot run (no repo).

NOTE: kept ASCII-only on purpose (Windows PowerShell 5.1 reads a BOM-less UTF-8 script as ANSI, so a
non-ASCII byte inside a script can garble output or even break parsing). Same rule as the other tools.
#>
param(
    [switch]$Fast,
    [string]$Range = '',
    [string]$Branch = '',
    [string]$RepoRoot = ''
)

$ErrorActionPreference = 'Stop'

$BuildGateCmd = '{{BUILD_GATE_CMD}}'
$TestCmd      = '{{TEST_CMD}}'
$SmokeCmd     = '{{SMOKE_CMD}}'

if (-not $RepoRoot) { $RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path) }
$script:Tools = Join-Path $RepoRoot 'tools'

# Both defaults used to be typed by hand at every call, and a typo there makes the gate look like it ran
# while it judged a different range (CONTRIBUTING.md section 6.1).
if (-not $Range) { $Range = 'origin/{{INTEGRATION_BRANCH}}...HEAD' }
if (-not $Branch) {
    # branch --show-current rather than rev-parse --abbrev-ref HEAD: the latter prints the literal "HEAD"
    # when the head is detached, which would silently make the governance claim check judge a branch name
    # that does not exist.
    $raw = & git -C $RepoRoot branch --show-current
    $Branch = ([string]::Join('', @($raw))).Trim()
    if (-not $Branch) { $Branch = 'unknown' }
}

$script:Results = New-Object System.Collections.ArrayList
$script:Failed = 0
$script:Unguarded = 0

function Split-CommandLine {
    param([string]$CommandLine)
    $parts = @($CommandLine.Trim() -split '\s+')
    $extra = @()
    if ($parts.Count -gt 1) { $extra = @($parts[1..($parts.Count - 1)]) }
    return @{ Command = [string]$parts[0]; Arguments = $extra }
}

# Runs one external command, captures merged stdout/stderr and the exit code.
# ErrorActionPreference is relaxed around the call: with 'Stop' in effect a child process writing to stderr
# raises a terminating error and the exit code would be lost.
function Invoke-Capture {
    param([string]$Command, [string[]]$Arguments)
    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        # The criteria run from the REPO ROOT, not from wherever this script happened to be started: the build
        # and test commands are documented without a path (they are stack placeholders), so a stray working
        # directory would make the gate judge a different tree - the same failure mode as passing the wrong
        # -Range, and just as invisible.
        Push-Location -LiteralPath $RepoRoot
        try {
            $text = (& $Command @Arguments 2>&1 | Out-String)
            $code = $LASTEXITCODE
        }
        finally {
            Pop-Location
        }
    }
    finally {
        $ErrorActionPreference = $previous
    }
    return [pscustomobject]@{ Text = $text; Code = $code }
}

function Write-StepResult {
    param(
        [string]$Name,
        [string]$Verdict,
        [double]$Seconds,
        [string]$Detail,
        [string]$Why,
        [int]$TailLines = 20
    )

    Write-Host ("  {0,-12} {1}  ({2:N1}s)" -f $Name, $Verdict, $Seconds)
    if ($Verdict -eq 'FAIL') {
        $script:Failed++
        if ($Detail) {
            $lines = $Detail -split "`r?`n" | Where-Object { $_.Trim() -ne '' }
            foreach ($line in ($lines | Select-Object -Last $TailLines)) { Write-Host ("      | " + $line.TrimEnd()) }
        }
    }
    elseif ($Verdict -eq 'UNGUARDED') {
        $script:Unguarded++
        if ($Why) { Write-Host ("      | " + $Why) }
    }
    $null = $script:Results.Add([pscustomobject]@{ Name = $Name; Verdict = $Verdict })
}

function Invoke-CommandStep {
    param([string]$Name, [string]$CommandLine)
    if (-not $CommandLine -or $CommandLine -like '<*') {
        Write-StepResult -Name $Name -Verdict 'UNGUARDED' -Seconds 0 -Detail '' -Why "no command was configured for this stack (CONTRIBUTING.md section 6.1) - UNGUARDED, not passed"
        return
    }
    $spec = Split-CommandLine $CommandLine
    if (-not (Get-Command $spec.Command -ErrorAction SilentlyContinue)) {
        Write-StepResult -Name $Name -Verdict 'UNGUARDED' -Seconds 0 -Detail '' -Why ("'{0}' is not on PATH here - cannot run this criterion" -f $spec.Command)
        return
    }
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $result = Invoke-Capture -Command $spec.Command -Arguments $spec.Arguments
    $watch.Stop()
    Write-StepResult -Name $Name -Verdict $(if ($result.Code -eq 0) { 'PASS' } else { 'FAIL' }) -Seconds $watch.Elapsed.TotalSeconds -Detail $result.Text
}

function Invoke-ScriptStep {
    param([string]$Name, [string]$RelativeScript, [string[]]$Arguments, [string]$MissingWhy = '')
    $path = Join-Path $script:Tools $RelativeScript
    if (-not (Test-Path -LiteralPath $path)) {
        if (-not $MissingWhy) { $MissingWhy = ("tools/{0} is not in this repo" -f $RelativeScript) }
        Write-StepResult -Name $Name -Verdict 'UNGUARDED' -Seconds 0 -Detail '' -Why ($MissingWhy + ' - UNGUARDED, not passed')
        return
    }
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $result = Invoke-Capture -Command 'powershell' -Arguments (@('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $path) + $Arguments)
    $watch.Stop()
    Write-StepResult -Name $Name -Verdict $(if ($result.Code -eq 0) { 'PASS' } else { 'FAIL' }) -Seconds $watch.Elapsed.TotalSeconds -Detail $result.Text
}

Write-Host ''
Write-Host '=== local verification ==='
Write-Host ("  mode   : {0}" -f $(if ($Fast) { 'fast (docs + board only)' } else { 'full' }))
Write-Host ("  range  : {0}" -f $Range)
Write-Host ("  branch : {0}" -f $Branch)
Write-Host ''

if (-not $Fast) {
    Invoke-CommandStep -Name 'build' -CommandLine $BuildGateCmd
    Invoke-CommandStep -Name 'test'  -CommandLine $TestCmd
}

Invoke-ScriptStep -Name 'governance' -RelativeScript 'governance-check.ps1' -Arguments @('-Range', $Range, '-Branch', $Branch, '-Strict', 'all')
Invoke-ScriptStep -Name 'metrics'    -RelativeScript 'metrics.ps1' -Arguments @('-Check')

# kanban is two commands: build regenerates the artifact, check judges the artifact - a gate that judges the
# TEMPLATE instead of the artifact would pass while the generated board is broken.
$kanbanCheck = Join-Path $script:Tools 'kanban-check.ps1'
if (-not (Test-Path -LiteralPath $kanbanCheck)) {
    Write-StepResult -Name 'kanban' -Verdict 'UNGUARDED' -Seconds 0 -Detail '' -Why 'tools/kanban-check.ps1 is not in this repo (the board is optional, CONTRIBUTING.md section 10) - UNGUARDED, not passed'
}
else {
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $build = Invoke-Capture -Command 'powershell' -Arguments @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', (Join-Path $script:Tools 'build-kanban.ps1'))
    if ($build.Code -ne 0) {
        $watch.Stop()
        Write-StepResult -Name 'kanban' -Verdict 'FAIL' -Seconds $watch.Elapsed.TotalSeconds -Detail $build.Text
    }
    else {
        $check = Invoke-Capture -Command 'powershell' -Arguments @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $kanbanCheck)
        $watch.Stop()
        Write-StepResult -Name 'kanban' -Verdict $(if ($check.Code -eq 0) { 'PASS' } else { 'FAIL' }) -Seconds $watch.Elapsed.TotalSeconds -Detail $check.Text
    }
}

# 6. smoke: the I1 trunk-runnable invariant. It is deliberately heavy, so -Fast skips it with build/test. The
# command is taken from the SAME placeholder the docs print: a criterion that paraphrases its carrier is how
# the two drift apart.
if (-not $Fast) {
    Invoke-CommandStep -Name 'smoke' -CommandLine $SmokeCmd
}

Write-Host ''
Write-Host '--- summary ---'
foreach ($row in $script:Results) { Write-Host ("  {0,-12} {1}" -f $row.Name, $row.Verdict) }
Write-Host ("  passed {0} / failed {1} / unguarded {2} (of {3})" -f ($script:Results.Count - $script:Failed - $script:Unguarded), $script:Failed, $script:Unguarded, $script:Results.Count)
Write-Host ''

if ($script:Failed -gt 0) {
    Write-Host 'RESULT: FAIL - see the criteria marked FAIL above.'
    if ($script:Unguarded -gt 0) { Write-Host ("  NOTE: {0} criterion/criteria printed UNGUARDED - that is a declared gap, not a pass (CONTRIBUTING.md section 8.1)." -f $script:Unguarded) }
    Write-Host 'NOTE: this is a SOFT guarantee - it only runs when a human runs it (CONTRIBUTING.md section 8.1).'
    exit 1
}

Write-Host 'RESULT: OK - all criteria passed.'
if ($script:Unguarded -gt 0) { Write-Host ("  WARNING: {0} criterion/criteria printed UNGUARDED - the run is clean only over what is actually guarded." -f $script:Unguarded) }
Write-Host 'NOTE: this is a SOFT guarantee - it only runs when a human runs it (CONTRIBUTING.md section 8.1).'
exit 0
